
INSERT INTO {table_prefix}layout_module VALUES
(null,{home_layout_id},"so_newletter_custom_popup.215","footer_block8","0"),
(null,{home_layout_id},"so_html_content.280","footer_block7","0"),
(null,{home_layout_id},"so_html_content.243","footer_block2","0"),
(null,{home_layout_id},"so_html_content.263","footer_block1","0"),
(null,{home_layout_id},"so_tools.375","content_top","2"),
(null,{home_layout_id},"so_quickview.247","content_top","1"),
(null,{home_layout_id},"so_page_builder.249","content_top","0"),
(null,{home_layout_id},"so_searchpro.257","content_search","0"),
(null,{home_layout_id},"so_megamenu.124","content_menu1","0"),
(null,{home_layout_id},"so_html_content.281","footer_block9","0");


INSERT INTO {table_prefix}soconfig VALUES
("72281","0","soconfig_general_store","{\"typelayout\":\"4\",\"themecolor\":\"blue\",\"preloader\":\"1\",\"preloader_animation\":\"circle-bounce2\",\"imgpreloader\":\"\",\"layouts\":\"1\",\"backtop\":\"1\",\"scroll_animation\":\"1\",\"copyright\":\"SO Revo \\u00a9 2016 - {year}. All Rights Reserved. Designed by &lt;a href=&quot;openfoxx.com&quot;&gt;openfoxx.Com&lt;\\/a&gt;\",\"typeheader\":\"4\",\"toppanel_status\":\"0\",\"toppanel_type\":\"2\",\"phone_status\":\"0\",\"contact_number\":{\"1\":\"\",\"2\":\"\"},\"welcome_message_status\":\"0\",\"welcome_message\":{\"1\":\"\",\"2\":\"\"},\"promotion_status\":\"0\",\"promotion\":{\"1\":\"\",\"2\":\"\"},\"wishlist_status\":\"1\",\"checkout_status\":\"0\",\"lang_status\":\"1\",\"typefooter\":\"4\",\"imgpayment_status\":\"1\",\"imgpayment\":\"catalog\\/demo\\/payment\\/payment.png\",\"type_banner\":\"6\",\"contentbg\":\"\"}","1"),
("72291","0","soconfig_advanced_store","{\"name_color\":\"orange\",\"theme_color\":\"#ff5e00\",\"scsscompile\":\"0\",\"scssformat\":\"Expanded\",\"compileMutiColor\":\"0\",\"minify_css\":\"0\",\"minify_js\":\"0\"}","1"),
("72301","0","soconfig_layout_store","{\"layoutstyle\":\"full\",\"general_bgcolor\":\"\",\"pattern\":\"none\",\"content_bg_mode\":\"repeat\",\"content_attachment\":\"scroll\"}","1"),
("72311","0","soconfig_pages_store","{\"product_catalog_refine\":\"2\",\"product_catalog_refine_col_lg\":\"6\",\"product_catalog_refine_col_md\":\"4\",\"product_catalog_refine_col_sm\":\"2\",\"product_catalog_refine_col_xs\":\"1\",\"deals_today\":\"1\",\"lstimg_cate_status\":\"1\",\"product_catalog_mode\":\"0\",\"product_catalog_column_lg\":\"3\",\"product_catalog_column_md\":\"3\",\"product_catalog_column_sm\":\"3\",\"product_catalog_column_xs\":\"2\",\"other_catalog_column_lg\":\"4\",\"other_catalog_column_md\":\"3\",\"other_catalog_column_sm\":\"2\",\"other_catalog_column_xs\":\"2\",\"secondimg\":\"2\",\"rating_status\":\"1\",\"lstdescription_status\":\"0\",\"sale_status\":\"1\",\"sale_text\":{\"1\":\"Sale\",\"2\":\"Sale\"},\"new_status\":\"1\",\"new_text\":{\"1\":\"New\",\"2\":\"New\"},\"days\":\"\",\"quick_status\":\"1\",\"quick_view_text\":{\"1\":\"Quick view\",\"2\":\"\"},\"discount_status\":\"1\",\"countdown_status\":\"1\",\"radio_style\":\"1\",\"check_style\":\"1\",\"product_gallerysize\":\"large\",\"thumbnails_position\":\"left\",\"product_enablezoom\":\"1\",\"product_zoommode\":\"inner\",\"product_zoomlenssize\":\"250\",\"tabs_position\":\"2\",\"product_page_button\":\"0\",\"product_socialshare\":{\"1\":\"\",\"2\":\"\"},\"related_status\":\"1\",\"related_position\":\"vertical\",\"product_related_column_lg\":\"1\",\"product_related_column_md\":\"1\",\"product_related_column_sm\":\"1\",\"product_related_column_xs\":\"1\"}","1"),
("72321","0","soconfig_fonts_store","{\"body_status\":\"google\",\"normal_body\":\"inherit\",\"url_body\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Open+Sans:400,600,700\",\"family_body\":\"Open Sans, sans-serif;\",\"selector_body\":\"body\",\"menu_status\":\"google\",\"normal_menu\":\"inherit\",\"url_menu\":\"https:\\/\\/fonts.googleapis.com\\/css?family=Raleway:600,700\",\"family_menu\":\"Raleway, sans-serif;\",\"selector_menu\":\".font-ct, h1, h2, h3, .static-menu a.main-menu, .container-megamenu.vertical .vertical-wrapper ul li &gt; a strong, .container-megamenu.vertical .vertical-wrapper ul.megamenu li .sub-menu .content .static-menu .menu ul li a.main-menu, .horizontal ul.megamenu &gt; li &gt; a, .footertitle, .module h3.modtitle span, .breadcrumb li a, .right-block .caption, .item-title a, .best-seller-custom .item-info, .product-box-desc, .product_page_price .price-new, .list-group-item a\",\"heading_status\":\"standard\",\"normal_heading\":\"inherit\",\"url_heading\":\"\",\"family_heading\":\"\",\"selector_heading\":\"\"}","1"),
("72331","0","soconfig_social_store","{\"social_fb_status\":\"0\",\"facebook\":\"\",\"social_twitter_status\":\"0\",\"twitter\":\"\",\"social_custom_status\":\"0\",\"video_code\":{\"1\":\"\",\"2\":\"\"}}","1"),
("72341","0","soconfig_custom_store","{\"cssinput_status\":\"0\",\"custom_css\":\"\",\"cssfile_status\":\"0\",\"cssfile\":[\"catalog\\/view\\/theme\\/so-revo\\/css\\/custom.css\"],\"jsinput_status\":\"0\",\"custom_js\":\"\",\"jsfile_status\":\"0\",\"jsfile\":[\"catalog\\/view\\/theme\\/so-revo\\/js\\/custom.js\"]}","1");


